version: '2'
services:
  splttr-api:
    env_file:
      - ./ENV
    restart: always
    build: .
    depends_on:
      - postgres
  postgres:
    env_file:
      - ./ENV
    restart: always
    image: postgres:9.6
    volumes:
      - postgres:/var/lib/postgresql/data
